# Generated by Django 5.1.5 on 2025-02-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='No title', max_length=256),
        ),
    ]
